# Imports

In [2]:
import numpy as np

# Test Data

In [12]:
example_data = [
    [0.885, 0.33,  9.1, 4],
    [0.725, 0.39, 10.9, 5],
    [0.560, 0.50,  9.4, 6],
    [0.735, 0.57,  9.8, 5],
    [0.610, 0.63,  8.4, 3],
    [0.260, 0.63, 11.8, 8],
    [0.500, 0.68, 10.5, 7],
    [0.320, 0.78, 10.0, 6],
]
data = np.array(example_data)
data_x, data_y = data[:,:-1], data[:,-1]

In [21]:
def corr_with_y(a, axis):
    return np.corrcoef(a, data_y)[0, 1]

# apply the function over the axis 0 of x
r = np.apply_over_axes(lambda a, axis: corr_with_y(a,axis), data_x, [0])

# r is a 1x3x1 array, where each element is the correlation of a column of x with y
print(r)

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [3]:
test_data = np.array([
    [np.random.rand(), np.random.random(), 21*np.random.random()],
    [np.random.rand(), np.random.random(), 21*np.random.random()],
    [np.random.rand(), np.random.random(), 21*np.random.random()],
])
test_data

array([[0.09055067, 0.09724103, 1.6605908 ],
       [0.19473596, 0.23044814, 3.50636422],
       [0.16117655, 0.39074927, 4.88453195]])

In [4]:
# 0 = feature_column_number
# 1= SplitVal
# 2 = left_tree_start_rel
# 3 = right_tree_start_rel]
points = np.array([
    [0.610, 0.63,  8.4, 3],
    [0.500, 0.68, 10.5, 7],
    [0.735, 0.57,  9.8, 5],
    [0.260, 0.63, 11.8, 8],
    [0.320, 0.78, 10.0, 6],
    [0.885, 0.33,  9.1, 4],
])

# Algorithms

**LinearRegression**

In [5]:
class LinRegLearner(object):  		  	   		 	   			  		 			     			  	 
    """  		  	   		 	   			  		 			     			  	 
    This is a Linear Regression Learner. It is implemented correctly.  		  	   		 	   			  		 			     			  	 
  		  	   		 	   			  		 			     			  	 
    :param verbose: If “verbose” is True, your code can print out information for debugging.  		  	   		 	   			  		 			     			  	 
        If verbose = False your code should not generate ANY output. When we test your code, verbose will be False.  		  	   		 	   			  		 			     			  	 
    :type verbose: bool  		  	   		 	   			  		 			     			  	 
    """  		  	   		 	   			  		 			     			  	 
    def __init__(self, verbose=False):  		  	   		 	   			  		 			     			  	 
        """  		  	   		 	   			  		 			     			  	 
        Constructor method  		  	   		 	   			  		 			     			  	 
        """  		  	   		 	   			  		 			     			  	 
        pass  # move along, these aren't the drones you're looking for  		  	   		 	   			  		 			     			  	 
  		  	   		 	   			  		 			     			  	 
    def author(self):  		  	   		 	   			  		 			     			  	 
        """  		  	   		 	   			  		 			     			  	 
        :return: The GT username of the student  		  	   		 	   			  		 			     			  	 
        :rtype: str  		  	   		 	   			  		 			     			  	 
        """  		  	   		 	   			  		 			     			  	 
        return "mshihab6"  # replace tb34 with your Georgia Tech username  		  	   		 	   			  		 			     			  	 
  		  	   		 	   			  		 			     			  	 
    def add_evidence(self, data_x, data_y):  		  	   		 	   			  		 			     			  	 
        """  		  	   		 	   			  		 			     			  	 
        Add training data to learner  		  	   		 	   			  		 			     			  	 
  		  	   		 	   			  		 			     			  	 
        :param data_x: A set of feature values used to train the learner  		  	   		 	   			  		 			     			  	 
        :type data_x: numpy.ndarray  		  	   		 	   			  		 			     			  	 
        :param data_y: The value we are attempting to predict given the X data  		  	   		 	   			  		 			     			  	 
        :type data_y: numpy.ndarray  		  	   		 	   			  		 			     			  	 
        """  		  	   		 	   			  		 			     			  	 
  		  	   		 	   			  		 			     			  	 
        # slap on 1s column so linear regression finds a constant term  		  	   		 	   			  		 			     			  	 
        new_data_x = np.ones([data_x.shape[0], data_x.shape[1] + 1])  		  	   		 	   			  		 			     			  	 
        new_data_x[:, 0 : data_x.shape[1]] = data_x  		  	   		 	   			  		 			     			  	 
  		  	   		 	   			  		 			     			  	 
        # build and save the model  		  	   		 	   			  		 			     			  	 
        self.model_coefs, residuals, rank, s = np.linalg.lstsq(  		  	   		 	   			  		 			     			  	 
            new_data_x, data_y, rcond=None  		  	   		 	   			  		 			     			  	 
        )  		  	   		 	   			  		 			     			  	 
  		  	   		 	   			  		 			     			  	 
    def query(self, points):  		  	   		 	   			  		 			     			  	 
        """  		  	   		 	   			  		 			     			  	 
        Estimate a set of test points given the model we built.  		  	   		 	   			  		 			     			  	 
  		  	   		 	   			  		 			     			  	 
        :param points: A numpy array with each row corresponding to a specific query.  		  	   		 	   			  		 			     			  	 
        :type points: numpy.ndarray  		  	   		 	   			  		 			     			  	 
        :return: The predicted result of the input data according to the trained model  		  	   		 	   			  		 			     			  	 
        :rtype: numpy.ndarray  		  	   		 	   			  		 			     			  	 
        """  		  	   		 	   			  		 			     			  	 
        return (self.model_coefs[:-1] * points).sum(axis=1) + self.model_coefs[  		  	   		 	   			  		 			     			  	 
            -1  		  	   		 	   			  		 			     			  	 
        ]  		  	   		 	   			  		 			     			  	 
    
    def __repr__(self):
        return(f"LinearRegression()")
    
    def __str__(self):
        return(f"LinearRegression()")
  		  	   		 	   			  		 			     			  	 
  		  	   		 	   			  		 			     			  	 
if __name__ == "__main__":  		  	   		 	   			  		 			     			  	 
    print("the secret clue is 'zzyzx'")  		  	   		 	   			  		 			     			  	 


the secret clue is 'zzyzx'


**Decision Tree Algorithm**
```
def build_tree(data):
    if data.shape[0]==1: return [leaf,data.y,np.nan,np.nan]
    if all data.y same: return [leaf,data.y,np.nan,np.nan]
    else
        determine best feature i to split on
        SplitVal = data[:,i].median()
        lefttree=build_tree(data[data[:,i]]<=SplitVal)
        righttree=build_tree(data[data[:,i]]>SplitVal)
        root = [i,SplitVal,1,lefttree.shape[0]+1]
        return (append(root,lefttree,righttree))
```

In [6]:
class DTLearner(object):

    # [x] __init__
    def __init__(self,leaf_size=1, verbose=False):
        """
        This is a Decision Tree Learner (DTLearner). You will need to properly implement this class as necessary.

        Parameters
            leaf_size (int)  - Is the maximum number of samples to be aggregated at a leaf
            verbose (bool)   - If “verbose” is True, your code can print out information for debugging.
                               If verbose = False your code should not generate ANY output. 
                               When we test your code, verbose will be False.
        """
        self.leaf_size=leaf_size
        self.verbose=verbose
        self.learner = None # Will be used when building and querying
    
    def __repr__(self):
        return(f"DTLearner(leaf_size={self.leaf_size}, verbose={self.verbose})")
    
    def __str__(self):
        return(f"DTLearner(leaf_size={self.leaf_size}, verbose={self.verbose})")
    
    # [x] add_evidence
    def add_evidence(self, data_x, data_y):
        """
            Add training data to learner

            Parameters
                data_x (numpy.ndarray) - A set of feature values used to train the learner
                data_y (numpy.ndarray) - The value we are attempting to predict given the X data
        """
        # data_x & data_y since the API requirements ask for it like that
        self.learner = self.build_tree(data_x,data_y).reshape([-1,4])
    
    # Note: Seperated from main buid_tree code to accomodate for inheritance of Random Tree Learner
    # [x] find_best_feature
    def find_best_feature(self, data_x, data_y):
        # Step 1: Correlation Matrix
        correlation_matrix = np.corrcoef(data_x,data_y,rowvar=False)
        # np.corrcoef to find the correlations between data_x and data_y
        # rowvar set to false since data_x & data_y don't have the same shapes
        # rowvar=False returns a correlation matrix where each column is compared with every column
        
        # Step 2: Extract the correlation array for our label column
        correlation_y = correlation_matrix[:-1,-1]
        # Since we only care about the correlation values with data_y, we only want the last column
        # The last column ends in a 1 since data_y will have a correlation of 1 with itself, so remove it
        
        # Step 3: Find the column that has the LARGEST correlation with label
        i = np.argmax(np.abs(correlation_y)) # This approach will automatically choose the first value if all are equal
        # argmax finds the maximum value and returns the position of it, which is what we care about in the end
        # Note, we care about finding the largest value in general, not the largest positive value, so we need to take the absolute value
        return i
    
    # Note: Seperated from main buid_tree code to accomodate for inheritance of Random Tree Learner
    # [x] find_SplitVal
    def find_SplitVal(self, data_x, i):
        SplitVal = np.median(data_x[:,i])
        return SplitVal
    
    # [x] build_tree
    def build_tree(self, data_x, data_y):
        """
            Building learner with given data using recurrsion

            Parameters
                data_x (numpy.ndarray) - A set of feature values used to train the learner
                data_y (numpy.ndarray) - The value we are attempting to predict given the X data
                
            Returns
                The numpy array that represents our tree

            Return type
                np.ndarray
        """
        # data_x & data_y since the API requirements ask for it like that
        
        # if there leaf_size number of rows, return
        if data_x.shape[0] <= self.leaf_size: 
            return np.array([-1, np.mean(data_y), np.nan, np.nan])
        
        # if there is only one value in y (example: y=[1,1,1,1,1,1]), return
        if len(np.unique(data_y)) == 1: return np.array([-1, data_y[0], np.nan, np.nan])
        
        # else: determine best feature i to split on
        i = self.find_best_feature(data_x, data_y)
        
        # Find the Split Value [median]
        SplitVal = self.find_SplitVal(data_x, i)
        LeftSplitCond = data_x[:,i]<=SplitVal
        # On the off chance that every condition in LeftSplitCond is all true or all false, return
        if (np.all((LeftSplitCond == False)) | np.all((LeftSplitCond == True))):
            return np.array([-1, np.mean(data_y), np.nan, np.nan])
        RightSplitCond = data_x[:,i]>SplitVal
        
        # Build Left Side of Tree
        leftdata_x,leftdata_y = data_x[LeftSplitCond], data_y[LeftSplitCond]
        lefttree = self.build_tree(leftdata_x,leftdata_y)
        
        # Build Right Side of Tree
        rightdata_x,rightdata_y = data_x[RightSplitCond], data_y[RightSplitCond]
        righttree = self.build_tree(rightdata_x,rightdata_y) 
        
        # Return Full Tree
        root = np.array([i, SplitVal, 1, lefttree.reshape([-1,4]).shape[0]+1]) 
        # Note: np.append was not working as intended. Used np.concatenate
        tree = np.concatenate([root,lefttree,righttree])
        return tree

    # [x] author
    def author(self):
        """
        Returns
            The GT username of the student

        Return type
            str
        """
        return "mshihab6"

    # TODO Check Output With Test
    # [x] query
    def query(self, points):
        """
        Estimate a set of test points given the model we built.

        Parameters
            points (numpy.ndarray) - A numpy array with each row corresponding to a specific query.

        Returns
            The predicted result of the input data according to the trained model

        Return type
            numpy.ndarray
        """
        ypred = np.array([])
        for point in points:
            i = 0
            node = 0
            while i >= 0:
                i = int(self.learner[node][0])
                if i < 0: break
                SplitVal = self.learner[node][1]
                SplitCon = point[i]<=SplitVal
                if SplitCon:
                    node += self.learner[node][2]
                else:
                    node += self.learner[node][3]
                node = int(node)
            ypred = np.append(ypred,self.learner[node][1])
        return ypred


**Random Tree Algorithm**
```
def build_tree(data):
    if data.shape[0]==1: return [leaf,data.y,np.nan,np.nan]
    if all data.y same: return [leaf,data.y,np.nan,np.nan]
    else
        determine random feature i to split on
        SplitVal = (data[random,i]+data[random,i])/2
        lefttree=build_tree(data[data[:,i]]<=SplitVal)
        righttree=build_tree(data[data[:,i]]>SplitVal)
        root = [i,SplitVal,1,lefttree.shape[0]+1]
        return (append(root,lefttree,righttree))
```

In [7]:
class RTLearner(object):

    # [x] __init__
    def __init__(self,leaf_size=1, verbose=False):
        """
        This is a Random Tree Learner (RTLearner). You will need to properly implement this class as necessary.

        Parameters
            leaf_size (int)  - Is the maximum number of samples to be aggregated at a leaf
            verbose (bool)   - If “verbose” is True, your code can print out information for debugging.
                               If verbose = False your code should not generate ANY output. 
                               When we test your code, verbose will be False.
        """
        self.leaf_size=leaf_size
        self.verbose=verbose
        self.learner = None # Will be used when building and querying
            
    def __repr__(self):
        return(f"RTLearner(leaf_size={self.leaf_size}, verbose={self.verbose})")
    
    def __str__(self):
        return(f"TTLearner(leaf_size={self.leaf_size}, verbose={self.verbose})")
    
    # [x] add_evidence
    def add_evidence(self, data_x, data_y):
        """
            Add training data to learner

            Parameters
                data_x (numpy.ndarray) - A set of feature values used to train the learner
                data_y (numpy.ndarray) - The value we are attempting to predict given the X data
        """
        # data_x & data_y since the API requirements ask for it like that
        self.learner = self.build_tree(data_x,data_y).reshape([-1,4])
    
    # [x] find_best_feature
    def find_best_feature(self, data_x):
        i = np.random.randint(0,data_x.shape[1])
        return i

    # [x] find_SplitVal
    def find_SplitVal(self, data_x, i):
        # random_row_1 = np.random.randint(0, data_x.shape[0])
        # random_row_2 = np.random.randint(0, data_x.shape[0])
        # while random_row_2 == random_row_1:
        #     random_row_2 = np.random.randint(0, data_x.shape[0])
        # SplitVal = (data_x[random_row_1,i]+data_x[random_row_2,i])/2
        SplitVal = np.median(data_x[:,i])
        return SplitVal
    
    # [x] build_tree
    def build_tree(self, data_x, data_y):
        """
            Building learner with given data using recurrsion

            Parameters
                data_x (numpy.ndarray) - A set of feature values used to train the learner
                data_y (numpy.ndarray) - The value we are attempting to predict given the X data
                
            Returns
                The numpy array that represents our tree

            Return type
                np.ndarray
        """
        # data_x & data_y since the API requirements ask for it like that
        
        # if there leaf_size number of rows, return
        if data_x.shape[0] <= self.leaf_size: 
            return np.array([-1, np.mean(data_y), np.nan, np.nan])
        
        # if there is only one value in y (example: y=[1,1,1,1,1,1]), return
        if len(np.unique(data_y)) == 1: return np.array([-1, data_y[0], np.nan, np.nan])
        
        # else: determine best feature i to split on
        i = self.find_best_feature(data_x)
        
        # Find the Split Value [median]
        SplitVal = self.find_SplitVal(data_x, i)
        LeftSplitCond = data_x[:,i]<=SplitVal
        # On the off chance that every condition in LeftSplitCond is all true or all false, return
        if (np.all((LeftSplitCond == False)) | np.all((LeftSplitCond == True))):
            return np.array([-1, np.mean(data_y), np.nan, np.nan])
        RightSplitCond = data_x[:,i]>SplitVal
        
        # Build Left Side of Tree
        leftdata_x,leftdata_y = data_x[LeftSplitCond], data_y[LeftSplitCond]
        lefttree = self.build_tree(leftdata_x,leftdata_y)
        
        # Build Right Side of Tree
        rightdata_x,rightdata_y = data_x[RightSplitCond], data_y[RightSplitCond]
        righttree = self.build_tree(rightdata_x,rightdata_y) 
        
        # Return Full Tree
        root = np.array([i, SplitVal, 1, lefttree.reshape([-1,4]).shape[0]+1]) 
        # Note: np.append was not working as intended. Used np.concatenate
        tree = np.concatenate([root,lefttree,righttree])
        return tree

    # [x] author
    def author(self):
        """
        Returns
            The GT username of the student

        Return type
            str
        """
        return "mshihab6"

    # TODO Check Output With Test
    # [x] query
    def query(self, points):
        """
        Estimate a set of test points given the model we built.

        Parameters
            points (numpy.ndarray) - A numpy array with each row corresponding to a specific query.

        Returns
            The predicted result of the input data according to the trained model

        Return type
            numpy.ndarray
        """
        ypred = np.array([])
        for point in points:
            i = 0
            node = 0
            while i >= 0:
                i = int(self.learner[node][0])
                if i < 0: break
                SplitVal = self.learner[node][1]
                SplitCon = point[i]<=SplitVal
                if SplitCon:
                    node += self.learner[node][2]
                else:
                    node += self.learner[node][3]
                node = int(node)
            ypred = np.append(ypred,self.learner[node][1])
        return ypred


**BagLearner**

In [8]:
class BagLearner(object):

    def __init__(self,learner, kwargs = {}, bags = 20, boost = False, verbose = False):
        """
        This is a Bootstrap Aggregataion Learner (BagLearner). You will need to properly implement this class as necessary.

        Parameters
            learner (learner) - Points to any arbitrary learner class that will be used in the BagLearner.
            kwargs            - Keyword arguments that are passed on to the learner's constructor and they can vary according to the learner
            bags (int)        - The number of learners you should train using Bootstrap Aggregation. 
                                If boost is true, then you should implement boosting (optional implementation).
            verbose (bool)    - If “verbose” is True, your code can print out information for debugging.
                                If verbose = False your code should not generate ANY output. When we test your code, verbose will be False.
        """
        self.learner = learner(**kwargs) # Define the Learner using the keyword arguments passed
        self.kwargs = kwargs # Keep track of keyword arguments
        self.bags = bags # Store the bag count
        self.boost = boost # Store the boolean boost value
        self.verbose = verbose # Store the boolean verbose value
        self.ensemble = np.array([self.learner for _ in range(self.bags)]) # create numpy array of learners to make an ensemble

    def __repr__(self):
        return(f"BagLearner(learner = {self.learner}, bags = {self.bags}, boost = {self.boost}, verbose = {self.verbose})")
    
    def __str__(self):
        return(f"BagLearner(learner = {self.learner}, bags = {self.bags}, boost = {self.boost}, verbose = {self.verbose})")
    
    def create_bags(self, m, data_x, data_y):
        n = len(data_x)
        bag_indexes = np.random.choice(n,size=(m,n),replace=True) # creates a numpy array of shape (m,n) of row numbers per bag
        bags = np.array([data_x[indexes,:] for indexes in bag_indexes]) # using each row numbers to create bags of shape (m,n,c) where c is the column number in data_x
        bag_ys = np.array([data_y[indexes] for indexes in bag_indexes]) # using each row numbers to create the ys for each bag of shape (m,n)
        return bags,bag_ys # return the created bags and their respective ys
    
    def add_evidence(self, data_x, data_y):
        """
        Add training data to learner

        Parameters
            data_x (numpy.ndarray) - A set of feature values used to train the learner
            data_y (numpy.ndarray) - The value we are attempting to predict given the X data
        """
        bags_array, bag_ys = self.create_bags(self.bags, data_x, data_y) # get all the bags and their respective ys
        for i, learner in enumerate(self.ensemble):
            # Gotta Love Enumerate!
            learner.add_evidence(bags_array[i],bag_ys[i]) # build learner from the bags created above
            # No need to make a build learner since each learner should have it already


    def author(self):
        """
        Returns
            The GT username of the student

        Return type
            str
        """
        return "mshihab6"


    def query(self, points):
        """
        Estimate a set of test points given the model we built.

        Parameters
            points (numpy.ndarray) - A numpy array with each row corresponding to a specific query.

        Returns
            The predicted result of the input data according to the trained model

        Return type
            numpy.ndarray
        """
        predictions = []
        for learner in self.ensemble:
            predictions.append(learner.query(points))
        avg = np.mean(np.array(predictions),axis=0)
        return np.mean(np.array(predictions),axis=0)

**InsaneLearner**

In [9]:
class InsaneLearner(object):
    def __init__(self, verbose=False):
        self.verbose=verbose
        self.learner = np.array([BagLearner(LinRegLearner) for _ in range(20)])
    def __repr__(self):return(f"InsaneLearner(learner = {self.learner}, verbose = {self.verbose})")
    def __str__(self):return(f"InsaneLearner(learner = {self.learner}, verbose = {self.verbose})")
    def add_evidence(self,data_x, data_y):
        for learner in self.learner: learner.add_evidence(data_x,data_y)
    def author(self): return "mshihab6"
    def query(self, points):
        predictions = []
        for learner in self.learner: predictions.append(learner.query(points))
        return np.mean(np.array(predictions),axis=0)

# Scratch

In [10]:
n = len(data_x)
m = 20

bag_indexes = np.random.choice(n,size=(m,n),replace=True)
bags = np.array([data_x[indexes,:] for indexes in bag_indexes])
bag_ys = np.array([data_y[indexes] for indexes in bag_indexes])

In [11]:
learners = np.array([RTLearner() for _ in range(5)])
for i, l in enumerate(learners):
    l.add_evidence(bags[i],bag_ys[i])
i = [3,6,2,1]
predictions = []

for idx, l in enumerate(learners):
    lq = l.query(data_x[i,:])
    print(idx, lq)
    predictions.append(lq)
avg = np.mean(np.array(predictions),axis=0)
print(avg)


0 [4.5 7.  4.5 5. ]
1 [5. 6. 6. 5.]
2 [5. 7. 8. 5.]
3 [5. 7. 6. 5.]
4 [4.75 6.   6.   4.75]
[4.85 6.6  6.1  4.95]


In [12]:
inf = open(r"C:\Users\macal\OneDrive\Documents\OMSCS\CS7647\assess_learners\Data\Istanbul.csv") 
data = np.array([list(map(str,s.strip().split(','))) for s in inf.readlines()])
# data = np.array([list(map(float, s.strip().split(','))) for s in inf.readlines()])
inf.close()

if data[0][0]=="date":
    data = data[1:,1:]

# compute how much of the data is training and testing  		  	   		 	   			  		 			     			  	 
train_rows = int(0.6 * data.shape[0])  		  	   		 	   			  		 			     			  	 
test_rows = data.shape[0] - train_rows  		  	   		 	   			  		 			     			  	 
                                                                            
# separate out training and testing data  		  	   		 	   			  		 			     			  	 
train_x = data[:train_rows, 0:-1].astype(float)  		  	   		 	   			  		 			     			  	 
train_y = data[:train_rows, -1].astype(float)  		  	   		 	   			  		 			     			  	 
test_x = data[train_rows:, 0:-1].astype(float)  		  	   		 	   			  		 			     			  	 
test_y = data[train_rows:, -1].astype(float)  

In [13]:
np.random.choice(10,size = 10, replace = True)

array([1, 4, 4, 0, 5, 2, 7, 8, 3, 0])

In [14]:
def create_bags(data_x, data_y):
        n = len(data_x)
        bags = list()
        bag_ys = list()
        indexes = np.random.choice(n, size = n, replace=True) # creates a numpy array of shape (n) of row numbers per bag
        bags = np.array(data_x[indexes,:]) # using each row numbers to create bags of shape (n,c) where c is the column number in data_x
        bag_ys = np.array(data_y[indexes]) # using each row numbers to create the ys for each bag of shape (n)
        return bags, bag_ys # return the created bags and their respective ys

In [15]:
test_bags, test_bag_ys = create_bags(data_x, data_y)

In [16]:
data_x, test_bags

(array([[ 0.885,  0.33 ,  9.1  ],
        [ 0.725,  0.39 , 10.9  ],
        [ 0.56 ,  0.5  ,  9.4  ],
        [ 0.735,  0.57 ,  9.8  ],
        [ 0.61 ,  0.63 ,  8.4  ],
        [ 0.26 ,  0.63 , 11.8  ],
        [ 0.5  ,  0.68 , 10.5  ],
        [ 0.32 ,  0.78 , 10.   ]]),
 array([[ 0.56,  0.5 ,  9.4 ],
        [ 0.26,  0.63, 11.8 ],
        [ 0.56,  0.5 ,  9.4 ],
        [ 0.32,  0.78, 10.  ],
        [ 0.26,  0.63, 11.8 ],
        [ 0.32,  0.78, 10.  ],
        [ 0.5 ,  0.68, 10.5 ],
        [ 0.56,  0.5 ,  9.4 ]]))

In [17]:
test_bag_ys

array([6., 8., 6., 6., 8., 6., 7., 6.])

In [19]:
np.random.RandomState(1481090005)  		  	   		 	   			  		 			     			  	 
bag_index = np.random.choice(range(train_x.shape[0]), train_x.shape[0], replace = True)
bag_index

array([170, 173, 220, 218, 134,  53, 276, 209, 165, 158, 132, 298, 216,
       150,  75,   6, 242,  83,  62, 131, 286, 309, 246, 235, 140, 146,
        57,  32,  34,  33,  40, 300, 243, 128,  74, 177, 163,  16, 184,
        57, 132, 182, 175,  45,  55, 150, 275, 147, 263, 175, 229,  26,
       243, 217, 293, 169,  60, 263,   8, 146, 230, 308, 120, 310, 206,
       151,  79, 164, 300, 102,  41, 234, 254, 148, 315, 115, 258, 154,
       121, 159,  43, 202,  92, 263,  74, 156, 260,  83,  51,  97, 294,
       161, 113, 181,  25, 147, 186, 136, 146, 274, 126, 320, 203,   3,
       285, 289, 164, 274, 238, 255,  29,  83, 313,  29,  37, 220,  76,
       228, 300, 258, 253, 160, 190,  82,  66, 294, 313, 257,  36, 129,
        31,  28,  67,  15, 180, 226, 277,  31, 139,  69, 194,  13, 172,
        64, 289,  28, 271,  23, 222,   1,   5,  92, 194, 185,  27, 238,
       172, 161,  48, 308, 282, 204,  11,  71, 228, 186, 132,  41, 287,
       170, 260,  54, 282,  89, 318, 150, 162,  23, 266, 141, 15

In [20]:
bag_1  = BagLearner(learner=RTLearner,kwargs={"leaf_size": 1},bags=1 ,boost=False,verbose=False)
bag_20 = BagLearner(learner=RTLearner,kwargs={"leaf_size": 1},bags=20,boost=False,verbose=False)
bag_1 .add_evidence(train_x,train_y)
bag_20.add_evidence(train_x,train_y)
preds_1 = bag_1 .query(test_x)
preds_20= bag_20.query(test_x)
corr1  = np.corrcoef(preds_1 , test_y)[0, 1]
corr20 = np.corrcoef(preds_20, test_y)[0, 1]
print(f"One-Bag Correlation: {corr1} vs 20-Bag Correlation: {corr20}")

One-Bag Correlation: 0.6287403923747064 vs 20-Bag Correlation: 0.5527748137407896


In [21]:
preds_1.shape

(215,)

In [27]:
test_y.shape

(215,)

# Metrics

In [127]:
import math
import sys

In [61]:
def RSME(y_true, y_pred):
    # rmse = math.sqrt(((y_true - y_pred) ** 2).sum() / y_true.shape[0])
    rmse = math.sqrt(np.mean((y_true - y_pred) ** 2))
    return rmse


In [62]:
def MAE(y_true, y_pred):
    mae = np.mean(np.abs(y_true - y_pred))
    return mae


In [139]:
def MAPE(y_true, y_pred):
    mape = np.mean(np.abs((y_true - y_pred) / y_true))
    return mape


In [64]:
def ME(y_true, y_pred):
    me = np.max(np.abs(y_true - y_pred))
    return me


In [175]:
eps = sys.float_info.min
eps

2.2250738585072014e-308

In [173]:
def R2(y_true, y_pred):
    eps = sys.float_info.min
    numerator = ((y_true-y_pred)**2).sum()
    denominator = max(eps,((y_true-y_true.mean())**2).sum())
    r2 = 1-(numerator/denominator)
    return max(0,r2),r2

In [7]:
import pandas as pd